# Generated by Django 5.2.4 on 2025-08-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Peut lire tous les livres')]},
        ),
    ]
